[project]
name = "lagga"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Frank Ockerman", email = "frank.ockerman@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
  "jax[cuda]>=0.8.0",
  "jaxlib>=0.8.0",
  "jaxtyping>=0.3.3",
  "lanctools",
  "numba>=0.62.1",
  "numpy>=2.3.4",
  "pandas>=2.3.3",
  "pgenlib>=0.93.0",
  "pyarrow>=21.0.0",
  "tqdm>=4.67.1",
  "typer>=0.20.0",
]

[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["ipython>=9.6.0"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
lanctools = { git = "https://github.com/frankp-0/lanctools" }

[project.scripts]
lagga = "lagga.cli:main_entry"
